version: '3'

services:
  php_apache:
    container_name: php_8.2_apache_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/html
    networks:
      - reseau_virtuel
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1.0
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql_8.1.0_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbzoo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - reseau_virtuel

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - reseau_virtuel        

volumes:
  db_data:

networks:
  reseau_virtuel: